service: source
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  iamRoleStatements:
      - Effect: Allow
        Action:
          - s3:*
        Resource: 
          - arn:aws:s3:::psstdynamodbbuckettest/* #provide the bucket name here
      - Effect: Allow
        Action:
          - dynamodb:*
        Resource:
          - arn:aws:dynamodb:us-east-1:774104967360:table/Business_PSST #Provice the arn of dynamodb table

functions:
  processS3Object:
    handler: handler.processS3Object
    events:
      - s3:
          bucket: psstdynamodbbuckettest
          event: s3:ObjectCreated:*
    timeout: 300
    memorySize: 3008
